name = "blocker-day"
main = "index.js"
compatibility_date = "2024-05-01"

[vars]
HOURS = "3"
PROBABILITY = "0.50"
NAME = "Blocker.day"
SEED = "default-seed"
SEED_VIA_URL = "false"
TIMEZONE = "America/Toronto"
DAYS = "21"
REDIRECT = "https://github.com/andesco/blocker.day"
